puts "*******Basic Array methods*********"
array_demo = Array(1..10)
puts "Your Array length is #{array_demo.length}."
puts "Value at index 7 is #{array_demo.at(7)}."
puts "First element of our array is #{array_demo.first}"
puts "Last element of our array is #{array_demo.last}"
puts "First 4 element of our array is #{array_demo.take(4)}."
puts "Elements are after 3 value is  #{array_demo.drop(3)}"
puts "Checking value = 3 is in array or not. => #{array_demo.include?(3)}"
puts "Adding element in array #{array_demo << 11}"
puts "deleting last element in array is #{array_demo.pop} and remain array is #{array_demo} "
puts "deleting specific element (ex. 6) in array is #{array_demo.delete(6)} and remain array is #{array_demo}"
puts "The reverse of our array is #{array_demo.reverse}"
puts "Concat the array #{array_demo.concat([11, 12, 13], [14, 15])}"
